data:
  gpu: 0
  in_memory: 1
  num_workers: 4 
  train_dataset: data/cifar_train.beton
  val_dataset: data/cifar_test.beton
experiment:
  root: experiments
  task: classification
  dataset: cifar
  model_type: vgg_group
  log_level: 0
lr:
  lr: 0.05
  lr_peak_epoch: 5
  lr_schedule_type: cyclic
training:
  batch_size: 512
  epochs: 100
  momentum: 0.9
  weight_decay: 5e-4
  label_smoothing: 0.1
validation:
  lr_tta: true
